workflows:
  ios-release:
    name: Solicap iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials # Bu grubun Codemagic'te tan覺ml覺 olmas覺 gerekir
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Web UI
        script: |
          keychain add-certificates
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
    integrations:
      app_store_connect: "App Store Connect" # Codemagic'teki entegrasyon ad覺
