// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMWVLVPxL3-dBJTMtfmghSecue7Csmf0',
    appId: '1:716122061074:android:435ad4f0e39fce3b83dbcb',
    messagingSenderId: '716122061074',
    projectId: 'solicap',
    storageBucket: 'solicap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyHy9aNIas5uKJAb2uQJJWocMlwKb4h0',
    appId: '1:716122061074:ios:84760e9b628f6d7b83dbcb',
    messagingSenderId: '716122061074',
    projectId: 'solicap',
    storageBucket: 'solicap.firebasestorage.app',
    iosBundleId: 'com.solicap.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3yskou1mz79HCq5Qlk6STUswr4Ret90',
    appId: '1:716122061074:web:f92fb77fc47a197583dbcb',
    messagingSenderId: '716122061074',
    projectId: 'solicap',
    authDomain: 'solicap.firebaseapp.com',
    storageBucket: 'solicap.firebasestorage.app',
  );

}